### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by imnu13674850462** [michaelneri/ICME2024RM3Team#1]
Hello,Dear authors, I am pleased to have read your published technical report. Regarding the code released on GitHub, I would like to inquire about the contents of the TUT 2020 USA dataset. Does it include all the dev and eval data? Is the 3-class dataset included? I am looking forward to your response and thank you very much.

**Comment by michaelneri** [comment]
Hello @imnu13674850462,

the TUT 2020 dataset used for pretraining in our work consists only of the development dataset, which can be downloaded from here https://zenodo.org/records/3819968.

I do not understand what you refer to "3-class dataset". Could you explain better?

Thanks for your interest,

Michael
